apiVersion: v1
kind: PersistentVolume
metadata:
  name: default
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  # Behavior when PersistentVolumeClaim is deleted.
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
  nfs:
    path: "/opt/nfs/default"
    server: 10.222.7.189
