apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  # Behavior when PersistentVolumeClaim is deleted.
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
  nfs:
    path: "/opt/nfs/gitlab/"
    server: 10.222.7.189
