apiVersion: v1
kind: PersistentVolume
metadata:
  name: ldap
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  # Behavior when PersistentVolumeClaim is deleted.
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: default
  mountOptions:
    - hard
  nfs:
    path: "/opt/nfs/ldap"
    server: 10.222.7.189
