apiVersion: v1
kind: PersistentVolume
metadata:
  name: redmine
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  # Behavior when PersistentVolumeClaim is deleted.
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
  nfs:
    path: "/opt/nfs/redmine"
    server: 10.222.7.189
